version: '3'
services:
  web:
    container_name: daikin-web-control
    restart: unless-stopped
    image: e1025735/daikin-web-control:latest
    ports:
      - "8000:80"
    environment:
      UNIT_1_IP: 192.168.1.10
